[project]
name = "to-feature-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hopsworks==4.2",
    "loguru>=0.7.3",
    "pyarrow>=22.0.0",
    "pydantic-settings>=2.10.1",
    "quixstreams>=3.23.1",
]
