version: '3.7'
name: technical-indicators-pipeline
networks:
  redpanda_network:
    external: true
    name: redpanda_network
services:
  trades:
    build:
      context: ../services/trades
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/trades/.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always

  candles:
    build:
      context: ../services/candles
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/candles/.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always

  technical-indicators:
    build:
      context: ../services/technical-indicators
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/technical-indicators/.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always

  to-feature-store:
    build:
      context: ../services/to-feature-store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/to-feature-store/.env
      - ../services/to-feature-store/hopsworks_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always
